"""初始迁移

Revision ID: aedba81a5c0f
Revises:
Create Date: 2026-06-04 10:47:02.169035+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "aedba81a5c0f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_user",
        sa.Column(
            "user_name",
            sa.String(length=50),
            nullable=False,
            comment="登陆账号",
        ),
        sa.Column(
            "nick_name", sa.String(length=50), nullable=False, comment="名字"
        ),
        sa.Column(
            "email", sa.String(length=100), nullable=True, comment="邮箱"
        ),
        sa.Column(
            "password", sa.String(length=256), nullable=False, comment="密码"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sys_user_user_name"), "sys_user", ["user_name"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sys_user_user_name"), table_name="sys_user")
    op.drop_table("sys_user")
    # ### end Alembic commands ###
