"""初始迁移

Revision ID: d3af3f1538fb
Revises:
Create Date: 2026-06-05 15:51:43.877300+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d3af3f1538fb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_permission",
        sa.Column(
            "permission_name",
            sa.String(length=50),
            nullable=False,
            comment="权限名",
        ),
        sa.Column(
            "parent_id", sa.Integer(), nullable=False, comment="父级权限id"
        ),
        sa.Column(
            "permission_key",
            sa.String(length=50),
            nullable=False,
            comment="权限标识",
        ),
        sa.Column(
            "permission_type",
            sa.Enum("MENU", "BUTTON", "API", "LINK", name="permissiontype"),
            nullable=False,
            comment="权限类型",
        ),
        sa.Column("sort", sa.Integer(), nullable=False, comment="权限排序"),
        sa.Column(
            "path", sa.String(length=200), nullable=True, comment="路由路径"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="逻辑删除标记"
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), nullable=True, comment="删除时间"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sys_role",
        sa.Column(
            "role_name", sa.String(length=50), nullable=False, comment="角色名"
        ),
        sa.Column(
            "role_key",
            sa.String(length=50),
            nullable=False,
            comment="角色键值",
        ),
        sa.Column(
            "description",
            sa.String(length=200),
            nullable=True,
            comment="角色描述",
        ),
        sa.Column("sort", sa.Integer(), nullable=False, comment="角色排序"),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="逻辑删除标记"
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), nullable=True, comment="删除时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_name"),
    )
    op.create_index(
        op.f("ix_sys_role_role_key"), "sys_role", ["role_key"], unique=True
    )
    op.create_table(
        "sys_user",
        sa.Column(
            "user_name",
            sa.String(length=50),
            nullable=False,
            comment="登陆账号",
        ),
        sa.Column(
            "nick_name", sa.String(length=50), nullable=False, comment="名字"
        ),
        sa.Column(
            "email", sa.String(length=100), nullable=True, comment="邮箱"
        ),
        sa.Column(
            "password", sa.String(length=256), nullable=False, comment="密码"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, comment="逻辑删除标记"
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), nullable=True, comment="删除时间"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sys_user_user_name"), "sys_user", ["user_name"], unique=True
    )
    op.create_table(
        "sys_role_permission",
        sa.Column("role_id", sa.Integer(), nullable=False, comment="用户id"),
        sa.Column(
            "permission_id", sa.Integer(), nullable=False, comment="角色id"
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["sys_permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["sys_role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "role_id", "permission_id", name="uq_role_permission"
        ),
    )
    op.create_table(
        "sys_user_role",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="用户id"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="角色id"),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["sys_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="uq_user_role"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sys_user_role")
    op.drop_table("sys_role_permission")
    op.drop_index(op.f("ix_sys_user_user_name"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_role_role_key"), table_name="sys_role")
    op.drop_table("sys_role")
    op.drop_table("sys_permission")
    # ### end Alembic commands ###
