"""修改字段描述

Revision ID: 250918b66b3f
Revises: 77443caff7c1
Create Date: 2026-06-06 09:42:43.817685+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "250918b66b3f"
down_revision: Union[str, Sequence[str], None] = "77443caff7c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sys_permission",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "sys_role",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "sys_user",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
        comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sys_user",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        comment=None,
        existing_comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "sys_role",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        comment=None,
        existing_comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "sys_permission",
        "is_deleted",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
        comment=None,
        existing_comment="逻辑删除标记",
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
