"""修改字段描述

Revision ID: 77443caff7c1
Revises: d3af3f1538fb
Create Date: 2026-06-06 09:25:56.667284+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "77443caff7c1"
down_revision: Union[str, Sequence[str], None] = "d3af3f1538fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

change_tables = ['sys_permission', 'sys_user', 'sys_role']
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    for table in change_tables:
        # 跳过 alembic_version 表
        if table == 'alembic_version':
            continue
        # 添加 is_deleted 字段
        op.alter_column(
            table,
            'is_deleted',
            type_=sa.Boolean(),
            nullable=False,
            default=False,
            server_default=sa.text('0')
        )
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
