"""添加聊天模型2

Revision ID: 241fef4d0ef6
Revises: 4d178209327b
Create Date: 2026-06-09 21:17:18.625868+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "241fef4d0ef6"
down_revision: Union[str, Sequence[str], None] = "4d178209327b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column(
            "session_id",
            sa.String(length=50),
            nullable=False,
            comment="会话id",
        ),
        sa.Column("content", mysql.LONGTEXT(), nullable=False, comment="消息"),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM",
                "USER",
                "ASSISTANT",
                "FUNCTION",
                "TOOL",
                name="messagerole",
            ),
            nullable=False,
            comment="消息角色",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=True, comment="消息名称"
        ),
        sa.Column(
            "tool_call_id",
            sa.String(length=50),
            nullable=True,
            comment="工具调用id",
        ),
        sa.Column(
            "last_time",
            sa.DateTime(),
            nullable=True,
            comment="最后一次提问时间",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=True, comment="逻辑删除标记"
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), nullable=True, comment="删除时间"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_message_session_id"),
        "chat_message",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "chat_session",
        sa.Column(
            "session_id",
            sa.String(length=50),
            nullable=False,
            comment="会话对外唯一表识",
        ),
        sa.Column(
            "name", sa.String(length=50), nullable=False, comment="会话名称"
        ),
        sa.Column(
            "last_time",
            sa.DateTime(),
            nullable=True,
            comment="最后一次提问时间",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="主键ID",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间",
        ),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=True, comment="逻辑删除标记"
        ),
        sa.Column(
            "deleted_at", sa.DateTime(), nullable=True, comment="删除时间"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_session_session_id"),
        "chat_session",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_session_session_id"), table_name="chat_session"
    )
    op.drop_table("chat_session")
    op.drop_index(
        op.f("ix_chat_message_session_id"), table_name="chat_message"
    )
    op.drop_table("chat_message")
    # ### end Alembic commands ###
