"""去除无效字段

Revision ID: 886049a5dbf1
Revises: 241fef4d0ef6
Create Date: 2026-06-09 21:30:59.372629+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "886049a5dbf1"
down_revision: Union[str, Sequence[str], None] = "241fef4d0ef6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message", "last_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message",
        sa.Column(
            "last_time",
            mysql.DATETIME(),
            nullable=True,
            comment="最后一次提问时间",
        ),
    )
    # ### end Alembic commands ###
