"""添加基础字段

Revision ID: c5270bb3e69e
Revises: 886049a5dbf1
Create Date: 2026-06-09 21:49:46.502776+08:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c5270bb3e69e"
down_revision: Union[str, Sequence[str], None] = "886049a5dbf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "chat_message",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.add_column(
        "chat_message",
        sa.Column(
            "deleted_id", sa.Integer(), nullable=True, comment="删除者id"
        ),
    )
    op.create_foreign_key(
        None, "chat_message", "sys_user", ["created_id"], ["id"]
    )
    op.create_foreign_key(
        None, "chat_message", "sys_user", ["deleted_id"], ["id"]
    )
    op.create_foreign_key(
        None, "chat_message", "sys_user", ["updated_id"], ["id"]
    )
    op.add_column(
        "chat_session",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "chat_session",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.add_column(
        "chat_session",
        sa.Column(
            "deleted_id", sa.Integer(), nullable=True, comment="删除者id"
        ),
    )
    op.create_foreign_key(
        None, "chat_session", "sys_user", ["updated_id"], ["id"]
    )
    op.create_foreign_key(
        None, "chat_session", "sys_user", ["deleted_id"], ["id"]
    )
    op.create_foreign_key(
        None, "chat_session", "sys_user", ["created_id"], ["id"]
    )
    op.add_column(
        "sys_permission",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "sys_permission",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.add_column(
        "sys_permission",
        sa.Column(
            "deleted_id", sa.Integer(), nullable=True, comment="删除者id"
        ),
    )
    op.create_foreign_key(
        None, "sys_permission", "sys_user", ["deleted_id"], ["id"]
    )
    op.create_foreign_key(
        None, "sys_permission", "sys_user", ["created_id"], ["id"]
    )
    op.create_foreign_key(
        None, "sys_permission", "sys_user", ["updated_id"], ["id"]
    )
    op.add_column(
        "sys_role",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "sys_role",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.add_column(
        "sys_role",
        sa.Column(
            "deleted_id", sa.Integer(), nullable=True, comment="删除者id"
        ),
    )
    op.create_foreign_key(None, "sys_role", "sys_user", ["deleted_id"], ["id"])
    op.create_foreign_key(None, "sys_role", "sys_user", ["updated_id"], ["id"])
    op.create_foreign_key(None, "sys_role", "sys_user", ["created_id"], ["id"])
    op.add_column(
        "sys_role_permission",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "sys_role_permission",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.create_foreign_key(
        None, "sys_role_permission", "sys_user", ["created_id"], ["id"]
    )
    op.create_foreign_key(
        None, "sys_role_permission", "sys_user", ["updated_id"], ["id"]
    )
    op.add_column(
        "sys_user",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "sys_user",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.add_column(
        "sys_user",
        sa.Column(
            "deleted_id", sa.Integer(), nullable=True, comment="删除者id"
        ),
    )
    op.create_foreign_key(None, "sys_user", "sys_user", ["updated_id"], ["id"])
    op.create_foreign_key(None, "sys_user", "sys_user", ["created_id"], ["id"])
    op.create_foreign_key(None, "sys_user", "sys_user", ["deleted_id"], ["id"])
    op.add_column(
        "sys_user_role",
        sa.Column(
            "created_id", sa.Integer(), nullable=True, comment="创建者id"
        ),
    )
    op.add_column(
        "sys_user_role",
        sa.Column(
            "updated_id", sa.Integer(), nullable=True, comment="更新者id"
        ),
    )
    op.create_foreign_key(
        None, "sys_user_role", "sys_user", ["updated_id"], ["id"]
    )
    op.create_foreign_key(
        None, "sys_user_role", "sys_user", ["created_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sys_user_role", type_="foreignkey")
    op.drop_constraint(None, "sys_user_role", type_="foreignkey")
    op.drop_column("sys_user_role", "updated_id")
    op.drop_column("sys_user_role", "created_id")
    op.drop_constraint(None, "sys_user", type_="foreignkey")
    op.drop_constraint(None, "sys_user", type_="foreignkey")
    op.drop_constraint(None, "sys_user", type_="foreignkey")
    op.drop_column("sys_user", "deleted_id")
    op.drop_column("sys_user", "updated_id")
    op.drop_column("sys_user", "created_id")
    op.drop_constraint(None, "sys_role_permission", type_="foreignkey")
    op.drop_constraint(None, "sys_role_permission", type_="foreignkey")
    op.drop_column("sys_role_permission", "updated_id")
    op.drop_column("sys_role_permission", "created_id")
    op.drop_constraint(None, "sys_role", type_="foreignkey")
    op.drop_constraint(None, "sys_role", type_="foreignkey")
    op.drop_constraint(None, "sys_role", type_="foreignkey")
    op.drop_column("sys_role", "deleted_id")
    op.drop_column("sys_role", "updated_id")
    op.drop_column("sys_role", "created_id")
    op.drop_constraint(None, "sys_permission", type_="foreignkey")
    op.drop_constraint(None, "sys_permission", type_="foreignkey")
    op.drop_constraint(None, "sys_permission", type_="foreignkey")
    op.drop_column("sys_permission", "deleted_id")
    op.drop_column("sys_permission", "updated_id")
    op.drop_column("sys_permission", "created_id")
    op.drop_constraint(None, "chat_session", type_="foreignkey")
    op.drop_constraint(None, "chat_session", type_="foreignkey")
    op.drop_constraint(None, "chat_session", type_="foreignkey")
    op.drop_column("chat_session", "deleted_id")
    op.drop_column("chat_session", "updated_id")
    op.drop_column("chat_session", "created_id")
    op.drop_constraint(None, "chat_message", type_="foreignkey")
    op.drop_constraint(None, "chat_message", type_="foreignkey")
    op.drop_constraint(None, "chat_message", type_="foreignkey")
    op.drop_column("chat_message", "deleted_id")
    op.drop_column("chat_message", "updated_id")
    op.drop_column("chat_message", "created_id")
    # ### end Alembic commands ###
